In [3]:
import numpy as np
from pyscf.pbc import gto, scf, cc

In [28]:
'''
CCSD with k-point sampling or at an individual k-point
'''
d = 2
a = 2
na = 2
nc = 1
elmt = 'H'
atoms = ""
for n in range(nc*na):
    shift = ((n - n % na) // na) * (d-a)
    atoms += f"{elmt} {n*a+shift:.5f} 0.00000 0.00000 \n"

cell = gto.Cell()
cell.atom= atoms
cell.a = np.eye(3)*3.5668
cell.unit = 'B'
cell.verbose = 5
cell.build()

#
# KHF and KCCSD with 2x2x2 k-points
#
kpts = cell.make_kpts([2,2,2])
kmf = scf.KRHF(cell).density_fit()
kmf.kpts = kpts
ehf = kmf.kernel()

mycc = cc.KCCSD(kmf)
mycc.kernel()
print("KRCCSD energy (per unit cell) =", mycc.e_tot)

System: uname_result(system='Linux', node='sharmagroup-rn', release='6.14.0-37-generic', version='#37~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 20 10:25:38 UTC 2', machine='x86_64')  Threads 16
Python 3.11.14 (main, Oct 21 2025, 18:31:21) [GCC 11.2.0]
numpy 2.3.1  scipy 1.16.2  h5py 3.14.0
Date: Fri Jan  9 11:58:26 2026
PySCF version 2.11.0
PySCF path  /home/sharmagroup/sharmagroup/pyscf
GIT HEAD (branch master) 3d1768f5e33b144b606c3d2c81c12ee54d794501

[ENV] PYSCF_EXT_PATH /home/sharmagroup/sharmagroup/pyscf-forge
[CONFIG] conf_file None
[INPUT] verbose = 5
[INPUT] max_memory = 4000 
[INPUT] num. atoms = 2
[INPUT] num. electrons = 2
[INPUT] charge = 0
[INPUT] spin (= nelec alpha-beta = 2S) = 0
[INPUT] symmetry False subgroup None
[INPUT] Mole.unit = B
[INPUT] Symbol           X                Y                Z      unit          X                Y                Z       unit  Magmom
[INPUT]  1 H      0.000000000000   0.000000000000   0.000000000000 AA    0.000000000000   0.000000000

In [26]:
kpts = cell.make_kpts([4,4,4])
print(kpts)

[[0.         0.         0.        ]
 [0.         0.         0.44039372]
 [0.         0.         0.88078744]
 [0.         0.         1.32118117]
 [0.         0.44039372 0.        ]
 [0.         0.44039372 0.44039372]
 [0.         0.44039372 0.88078744]
 [0.         0.44039372 1.32118117]
 [0.         0.88078744 0.        ]
 [0.         0.88078744 0.44039372]
 [0.         0.88078744 0.88078744]
 [0.         0.88078744 1.32118117]
 [0.         1.32118117 0.        ]
 [0.         1.32118117 0.44039372]
 [0.         1.32118117 0.88078744]
 [0.         1.32118117 1.32118117]
 [0.44039372 0.         0.        ]
 [0.44039372 0.         0.44039372]
 [0.44039372 0.         0.88078744]
 [0.44039372 0.         1.32118117]
 [0.44039372 0.44039372 0.        ]
 [0.44039372 0.44039372 0.44039372]
 [0.44039372 0.44039372 0.88078744]
 [0.44039372 0.44039372 1.32118117]
 [0.44039372 0.88078744 0.        ]
 [0.44039372 0.88078744 0.44039372]
 [0.44039372 0.88078744 0.88078744]
 [0.44039372 0.88078744 1.32

In [17]:
eris = mycc.ao2mo()
print(eris)

    CPU time for vj and vk      3.82 sec, wall time      0.24 sec
Ewald components = 6.67551932418264e-05, -0.242104903343734, 0.0431695909366997
using incore ERI storage
    CPU time for CCSD integral transformation    107.04 sec, wall time      6.80 sec


In [27]:
kmf.kpts = kpts
s1e = kmf.get_ovlp()
print(s1e.shape)

(64, 2, 2)


In [22]:
kmf.get_hcore().shape

(8, 2, 2)

In [20]:
eris.oooo

array([[[[[[[ 2.94614335e-03-1.52263893e-21j,
              0.00000000e+00-0.00000000e+00j],
            [ 0.00000000e+00-0.00000000e+00j,
              0.00000000e+00-0.00000000e+00j]],

           [[ 0.00000000e+00-0.00000000e+00j,
              0.00000000e+00-0.00000000e+00j],
            [ 0.00000000e+00-0.00000000e+00j,
              0.00000000e+00-0.00000000e+00j]]],


          [[[ 0.00000000e+00-0.00000000e+00j,
              0.00000000e+00-0.00000000e+00j],
            [ 0.00000000e+00-0.00000000e+00j,
              0.00000000e+00-0.00000000e+00j]],

           [[ 0.00000000e+00-0.00000000e+00j,
              0.00000000e+00-0.00000000e+00j],
            [ 0.00000000e+00-0.00000000e+00j,
              0.00000000e+00-0.00000000e+00j]]]],



         [[[[ 5.77602627e-02-3.89640283e-18j,
              0.00000000e+00+0.00000000e+00j],
            [ 0.00000000e+00+0.00000000e+00j,
              0.00000000e+00+0.00000000e+00j]],

           [[ 0.00000000e+00+0.00000000e+00j,
        